### PR TITLE
[#100] [Bug] Notification Subject Type doesn't handle correctly

### LINKED ISSUE #100: [Bug] Notification Subject Type doesn't handle correctly
## Issue

Currently, `NotificationSubjectType` handle with capitalized which will map to `unknown` case instead. As subject types from API responses have capitalized like `PullRequest` and `NotificationSubjectType` enum should be camel case instead.
 
## Expected

`NotificationSubjectType` should handle with camel case for example `pullRequest`.
 
## Steps to reproduce

1. Run the app
2. Receive notifications
3. Debug `NotificationSubjectType` from `APINotification`

### PR DESCRIPTION
**Pull request by llleyelll**
Resolves #100 

## What happened 👀

- Update `NotificationSubjectType` mapping logic 
 
## Insight 📝

- Add String extension for camel case
 
## Proof Of Work 📹
Screen Shot 2021-09-24 at 12 01 31 PM

### CODE REVIEW

File: Source/Extensions/String+CamelCase.swift [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+    }
+
+    var lowercasingFirst: String {
+        return prefix(1).lowercased() + dropFirst()
+    }
+
+    var camelized: String {
+        guard !isEmpty else { return "" }
+        let parts = components(separatedBy: CharacterSet.alphanumerics.inverted)
+        let first = String(describing: parts.first!).lowercasingFirst
```
Comment (blyscuit) [inline Source/Extensions/String+CamelCase.swift:24]: Let's use optional instead or you can use `guard` too
```suggestion
        let parts = components(separatedBy: CharacterSet.alphanumerics.inverted)
        let first = String(describing: parts.first ?? "").lowercasingFirst
```

**Review by blyscuit — APPROVED** [review]

**Review by suho — APPROVED** [review]
